<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestionMatricula.Dto\GestionMatricula.Dto.csproj" />
    <ProjectReference Include="..\GestionMatricula.Entidades\GestionMatricula.Entidades.csproj" />
    <ProjectReference Include="..\GestionMatricula.Repositorios\GestionMatricula.Repositorios.csproj" />
  </ItemGroup>

</Project>
