<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccesoDatos\GestionMatricula.AccesoDatos.csproj" />
    <ProjectReference Include="..\GestionMatricula.Entidades\GestionMatricula.Entidades.csproj" />
  </ItemGroup>

</Project>
